#!/usr/bin/env python
import os


def options(opt):
    pass

def configure(conf):
    conf.check_cxx( header_name='isix_config.h', features='cxx',
            define_name='HAVE_ISIX_CONFIG_H' )


def build(bld):
    src = ['src/dts.cpp', 'src/L3GD20.cpp', 'src/LSM303.cpp', 'src/common.cpp']
    src += ['src/spi.cpp']
    # src += ['src/i2c.cpp']
    cppflags = ['-DISIX ']
    bld.program(
        features     = 'objcopy',
        target       = 'spi_i2c',
        source       = src,
        install_path = False,
        includes     = [ 'include' ],
        use          = [ 'isix', 'periph', 'foundation', 'stm32f411ed_boot' ],
        cxxflags     = cppflags
    )
