#!/usr/bin/env python
import os


def options(opt):
    pass

def configure(conf):
    conf.check_cxx( header_name='isix_config.h', features='cxx',
            define_name='HAVE_ISIX_CONFIG_H' )


def build(bld):
    src = [ 'src/dts.cpp' ]
    src += ['src/frequency_measure.cpp']
    bld.program(
        features     = 'objcopy',
        target       = 'timer',
        source       = src,
        install_path = False,
        includes     = [ '.' ],
        use          = [ 'isix', 'periph', 'foundation', 'stm32f411ed_boot' ],
        cxxflags     = [ 
            # '-D TIMER_INTERRUPT',
            # '-D PWM',
            # '-D SQUARE_WAVE',
            # '-D FREQUENCY_MEASURE'
        ]
    )
